Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "db-foodlove"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "./../../ansible", "/vagrant/ansible"

  config.vm.network "private_network", ip: "192.168.100.2"
  config.vm.network "forwarded_port", guest: 3306, host: 13306

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/db_foodlove.yml"
    ansible.provisioning_path = "/vagrant/ansible"
  end
end
