---

- name: Clone git repository
  become_user: "{{ cdn_imbo_application_name }}"
  git:
    repo: git@github.com:microservices-playground/cdn-imbo.git
    dest: "{{ cdn_imbo_root }}/code"
    accept_hostkey: yes
    version: master

- name: Install dependencies
  become_user: "{{ cdn_imbo_application_name }}"
  make:
    chdir: "{{ cdn_imbo_root }}/code"
    target: install
