---

dependencies:

  - role: geerlingguy.mysql
    become: yes
    mysql_databases:
      - name: foodlove
    mysql_users:
      - name: foodlove
        host: "%"
        password: foodlove
        priv: "foodlove.*:ALL"
