---

dependencies:

  - role: geerlingguy.mysql
    become: yes
    mysql_databases:
      - name: "{{ db_foodlove.db_name }}"
    mysql_users:
      - name: "{{ db_foodlove.db_username }}"
        host: "%"
        password: "{{ db_foodlove.db_password }}"
        priv: "{{ db_foodlove.db_name }}.*:ALL"
