---

- name: Copy db dump to guest
  copy:
    src: files/comments.sql
    dest: /tmp

- name: Import the database dump
  mysql_db:
    name: "{{ db_comments.db_name }}"
    state: import
    target: /tmp/comments.sql
    login_user: "{{ db_comments.db_username }}"
    login_password: "{{ db_comments.db_password }}"

- name: Remove db dump
  file:
    path: /tmp/comments.sql
    state: absent
