---

- name: Install python dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { name: flask, version: 0.11.1 }
    - { name: flask_cors, version: 3.0.2 }
    - { name: mongoalchemy, version: 0.21 }

- name: Clone git repository
  become_user: "{{ api_activities_application_name }}"
  git:
    repo: git@github.com:microservices-playground/api-activities.git
    dest: "{{ api_activities_root }}/code"
    accept_hostkey: yes
    version: master

- name: Configure application
  become_user: "{{ api_activities_application_name }}"
  template:
    src: config.yml.j2
    dest: "{{ api_activities_root }}/code/config.yml"
    mode: "0644"

- name: Open port for application
  ufw:
    rule: allow
    port: "{{ api_activities_port }}"

- name: Restart application
  supervisorctl:
    name: "{{ api_activities_application_name }}"
    state: restarted
