---

dependencies:

  - role: greendayonfire.mongodb
    become: yes
    mongodb_user_admin_name: admin
    mongodb_user_admin_password: admin
    mongodb_root_admin_name: root
    mongodb_root_admin_password: root
    mongodb_security_authorization: "enabled"
    mongodb_net_bindip: 0.0.0.0
    mongodb_net_port: "{{ db_imbo.port }}"
    mongodb_users:
      - name: "{{ db_imbo.username }}"
        password: "{{ db_imbo.password }}"
        roles: readWrite
        database: "{{ db_imbo.collection }}"
