Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "./../ansible", "/vagrant/ansible"

  config.vm.define "db_foodlove" do |db_foodlove|
    db_foodlove.vm.hostname = "db-foodlove"
    db_foodlove.vm.network "private_network", ip: "192.168.100.2"
    db_foodlove.vm.network "forwarded_port", guest: 3306, host: 13306

    db_foodlove.vm.provider "virtualbox" do |v|
      v.memory = 768
      v.cpus = 1
    end

    db_foodlove.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/db_foodlove.yml"
      ansible.provisioning_path = "/vagrant/ansible"
    end
  end

  config.vm.define "db_comments" do |db_comments|
    db_comments.vm.hostname = "db-comments"
    db_comments.vm.network "private_network", ip: "192.168.100.3"
    db_comments.vm.network "forwarded_port", guest: 3306, host: 23306

    db_comments.vm.provider "virtualbox" do |v|
      v.memory = 768
      v.cpus = 1
    end

    db_comments.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/db_comments.yml"
      ansible.provisioning_path = "/vagrant/ansible"
    end
  end

  config.vm.define "db_activities" do |db_activities|
    db_activities.vm.hostname = "db-activities"
    db_activities.vm.network "private_network", ip: "192.168.100.4"
    db_activities.vm.network "forwarded_port", guest: 27017, host: 37017

    db_activities.vm.provider "virtualbox" do |v|
      v.memory = 768
      v.cpus = 1
    end

    db_activities.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/db_activities.yml"
      ansible.provisioning_path = "/vagrant/ansible"
    end
  end

  config.vm.define "io_rabbitmq" do |io_rabbitmq|
    io_rabbitmq.vm.hostname = "io-rabbitmq"
    io_rabbitmq.vm.network "private_network", ip: "192.168.100.50"
    io_rabbitmq.vm.network "forwarded_port", guest: 5672, host: 5672
    io_rabbitmq.vm.network "forwarded_port", guest: 15672, host: 15672

    io_rabbitmq.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    io_rabbitmq.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/io_rabbitmq.yml"
      ansible.provisioning_path = "/vagrant/ansible"
    end
  end

  config.vm.define "api_comments" do |api_comments|
    api_comments.vm.hostname = "api-comments"
    api_comments.vm.network "private_network", ip: "192.168.100.100"
    api_comments.vm.network "forwarded_port", guest: 80, host: 8080

    api_comments.vm.synced_folder "~/Repositories/foodlove/api-comments", "/srv/api_comments/code", type: "nfs"

    api_comments.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    api_comments.vm.provision "ansible_local" do |ansible|
      ansible.install_mode = "pip"
      ansible.version = "2.1.3.0"
      ansible.playbook = "playbooks/api_comments.yml"
      ansible.provisioning_path = "/vagrant/ansible"
    end
  end

  config.vm.define "api_activities" do |api_comments|
    api_comments.vm.hostname = "api-activities"
    api_comments.vm.network "private_network", ip: "192.168.100.101"
    api_comments.vm.network "forwarded_port", guest: 5000, host: 5050

    api_comments.vm.synced_folder "~/Repositories/foodlove/api-activities", "/srv/api_activities/code", type: "nfs"

    api_comments.vm.provider "virtualbox" do |v|
      v.memory = 768
      v.cpus = 1
    end

    api_comments.vm.provision "ansible_local" do |ansible|
      ansible.install_mode = "pip"
      ansible.version = "2.1.3.0"
      ansible.playbook = "playbooks/api_activities.yml"
      ansible.provisioning_path = "/vagrant/ansible"
      ansible.extra_vars = {
        'env' => 'prod'
      }
    end
  end

end
