---

dependencies:
  - role: geerlingguy.php
    become: yes
    php_enable_php_fpm: true
    php_webserver_daemon: nginx
    php_date_timezone: Europe/London
    php_fpm_listen: /var/run/php7.0-fpm.sock
    php_packages:
      - php7.0-common
      - php7.0-fpm
      - php7.0-xdebug
      - php7.0-intl
      - php7.0-mbstring
      - php7.0-curl
      - php7.0-json
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-xml

  - role: jdauphant.nginx
    become: yes
    nginx_sites:
      default:
        - listen 80
        - server_name _
        - root "/srv/code/web"
        - error_log /srv/log/nginx-error.log
        - access_log /srv/log/nginx-access.log
        - location / {
            try_files $uri /app.php$is_args$args;
          }
        - location ~ ^/(app_dev|config)\.php(/|$) {
            fastcgi_pass unix:/var/run/php7.0-fpm.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
          }
        - location ~ ^/app\.php(/|$) {
            fastcgi_pass unix:/var/run/php7.0-fpm.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            internal;
          }
        - location ~ \.php$ {
            return 404;
          }
