---

dependencies:
  - role: application
    application_name: "{{ cdn_imbo_application_name }}"

  - role: geerlingguy.php
    become: yes
    php_enable_php_fpm: true
    php_fpm_pool_user: "{{ cdn_imbo_application_name }}"
    php_fpm_pool_group: "{{ cdn_imbo_application_name }}"
    php_fpm_pm_max_children: 200
    php_fpm_pm_start_servers: 5
    php_fpm_pm_min_spare_servers: 3
    php_fpm_pm_max_spare_servers: 7
    php_webserver_daemon: nginx
    php_date_timezone: Europe/London
    php_fpm_listen: "{{ cdn_imbo_root }}/run/cdn_imbo-fpm.sock"
    php_packages:
      - php7.0-apcu
      - php7.0-bcmath
      - php7.0-common
      - php7.0-curl
      - php7.0-fpm
      - php7.0-imagick
      - php7.0-intl
      - php7.0-json
      - php7.0-mbstring
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-xml
      - php-mongodb

  - role: jdauphant.nginx
    become: yes
    nginx_sites:
      default:
        - listen {{ cdn_imbo_port }}
        - server_name _
        - root "{{ cdn_imbo_root }}/code/vendor/imbo/imbo/public"
        - index index.php
        - error_log "{{ cdn_imbo_root }}/log/nginx-error.log"
        - access_log "{{ cdn_imbo_root }}/log/nginx-access.log"
        - location / {
              try_files $uri $uri/ /index.php?$args;
              location ~ \.php$ {
                  fastcgi_pass unix:{{ cdn_imbo_root }}/run/cdn_imbo-fpm.sock;
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME {{ cdn_imbo_root }}/vendor/imbo/imbo/public/index.php;
                  include fastcgi_params;
              }
          }
