---

dependencies:
  - role: application
    application_name: "{{ cdn_imbo_application_name }}"

  - role: geerlingguy.php
    become: yes
    php_enable_php_fpm: true
    php_fpm_pool_user: "{{ cdn_imbo_application_name }}"
    php_fpm_pool_group: "{{ cdn_imbo_application_name }}"
    php_fpm_pm_max_children: 200
    php_fpm_pm_start_servers: 5
    php_fpm_pm_min_spare_servers: 3
    php_fpm_pm_max_spare_servers: 7
    php_webserver_daemon: nginx
    php_fpm_daemon: php5.6-fpm
    php_fpm_conf_path: /etc/php/5.6/fpm
    php_fpm_pool_conf_path: /etc/php/5.6/fpm/pool.d/www.conf
    php_date_timezone: Europe/London
    php_fpm_listen: "{{ cdn_imbo_root }}/run/cdn_imbo-fpm.sock"
    php_conf_paths:
      - /etc/php/5.6/fpm
      - /etc/php/5.6/apache2
      - /etc/php/5.6/cli
    php_extension_conf_paths:
      - /etc/php/5.6/fpm/conf.d
      - /etc/php/5.6/apache2/conf.d
      - /etc/php/5.6/cli/conf.d
    php_packages:
      - php5.6-bcmath
      - php5.6-common
      - php5.6-curl
      - php5.6-fpm
      - php5.6-imagick
      - php5.6-intl
      - php5.6-json
      - php5.6-mbstring
      - php5.6-mcrypt
      - php5.6-mysql
      - php5.6-xml
      - php-mongodb

  - role: jdauphant.nginx
    become: yes
    nginx_sites:
      default:
        - listen {{ cdn_imbo_port }}
        - server_name _
        - root "{{ cdn_imbo_root }}/code/vendor/imbo/imbo/public"
        - index index.php
        - error_log "{{ cdn_imbo_root }}/log/nginx-error.log"
        - access_log "{{ cdn_imbo_root }}/log/nginx-access.log"
        - location / {
            try_files $uri $uri/ /index.php?$args;
            location ~ \.php$ {
                fastcgi_pass unix:{{ cdn_imbo_root }}/run/cdn_imbo-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME {{ cdn_imbo_root }}/vendor/imbo/imbo/public/index.php;
                include fastcgi_params;
            }
          }
