---

- name: Create group for applicaiton
  group:
    name: "{{ application_name }}"

- name: Create system user for application
  user:
    name: "{{ application_name }}"
    group: "{{ application_name }}"
    home: "/srv/{{ application_name }}"
    shell: /bin/bash

- name: Ensure home directory is owned by user
  file:
    path: "/srv/{{ application_name }}"
    owner: "{{ application_name }}"
    group: "{{ application_name }}"

- name: Create directories
  file:
    path: "/srv/{{ application_name }}/{{ item }}"
    state: directory
    owner: "{{ application_name }}"
    group: "{{ application_name }}"
  with_items:
    - log
    - run
    - tmp
    - .ssh

- name: Copy ssh keys
  copy:
    src: "{{ item.file }}"
    dest: "/srv/{{ application_name }}/.ssh"
    owner: "{{ application_name }}"
    group: "{{ application_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { file: id_rsa, mode: "0600"}
    - { file: id_rsa.pub, mode: "0644" }

- name: Check if code directory exists
  stat:
    path: "/srv/{{ application_name }}/code"
  register: code_exists

- name: Create code directory if it does not exist
  file:
    path: "/srv/{{ application_name }}/code"
    state: directory
    owner: "{{ application_name }}"
    group: "{{ application_name }}"
  when: code_exists.stat.isdir is not defined
